-- MySQL Script generated by MySQL Workbench
-- 10/26/16 15:27:18
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome_cliente` VARCHAR(45) NULL,
  `endereco_cliente` VARCHAR(45) NULL,
  `cpf_cliente` VARCHAR(45) NULL,
  `rg_cliente` VARCHAR(45) NULL,
  `telefone_cliente` VARCHAR(45) NULL,
  `e-mail_cliente` VARCHAR(100) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `idServico` INT NOT NULL,
  `tipo_servico` INT NULL,
  `dataDeAbertura_servico` DATE NULL,
  `orcamento_servico` DOUBLE NULL,
  `etapa_servico` INT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idServico`),
  INDEX `fk_Servico_Cliente_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Servico_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mostruario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mostruario` (
  `idMostruario` INT NOT NULL,
  `nome_Mostruario` VARCHAR(45) NULL,
  `Imagem_Mostruario` BLOB NULL,
  `Servico_idServico` INT NOT NULL,
  PRIMARY KEY (`idMostruario`),
  INDEX `fk_Mostruario_Servico1_idx` (`Servico_idServico` ASC),
  CONSTRAINT `fk_Mostruario_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
